version: "3.8"

services:
  react-dev:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    container_name: react_dev
    command: npm run dev -- --host

  react-prod:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:80"
    container_name: react_prod
